version: '2'
services:
  sensor-watcher-image:
    build: .
    image: sensor-watcher-image
    container_name: sensor-watcher-container
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    environment:
      - MONGODB_CONN_STR=mongodb://mongodb:27017/sensors
    links:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo-db-container
    ports:
      - "27017:27017"